version: '3.8'

services:
  # -------------------------
  # Redis Node 1
  # -------------------------
  redis-node-1:
    image: redis:7.0-alpine
    container_name: redis-node-1
    networks:
      - redis-cluster
    command: >
      redis-server
        --port 7001
        --cluster-enabled yes
        --cluster-config-file nodes.conf
        --cluster-node-timeout 5000
        --appendonly yes
        --bind 0.0.0.0
        --cluster-announce-ip 172.16.7.71
        --cluster-announce-port 7001
        --cluster-announce-bus-port 17001
    ports:
      - "7001:7001"
      - "17001:17001"

  # -------------------------
  # Redis Node 2
  # -------------------------
  redis-node-2:
    image: redis:7.0-alpine
    container_name: redis-node-2
    networks:
      - redis-cluster
    command: >
      redis-server
        --port 7002
        --cluster-enabled yes
        --cluster-config-file nodes.conf
        --cluster-node-timeout 5000
        --appendonly yes
        --bind 0.0.0.0
        --cluster-announce-ip 172.16.7.71
        --cluster-announce-port 7002
        --cluster-announce-bus-port 17002
    ports:
      - "7002:7002"
      - "17002:17002"

  # -------------------------
  # Redis Node 3
  # -------------------------
  redis-node-3:
    image: redis:7.0-alpine
    container_name: redis-node-3
    networks:
      - redis-cluster
    command: >
      redis-server
        --port 7003
        --cluster-enabled yes
        --cluster-config-file nodes.conf
        --cluster-node-timeout 5000
        --appendonly yes
        --bind 0.0.0.0
        --cluster-announce-ip 172.16.7.71
        --cluster-announce-port 7003
        --cluster-announce-bus-port 17003
    ports:
      - "7003:7003"
      - "17003:17003"

  # -------------------------
  # Redis Node 4
  # -------------------------
  redis-node-4:
    image: redis:7.0-alpine
    container_name: redis-node-4
    networks:
      - redis-cluster
    command: >
      redis-server
        --port 7004
        --cluster-enabled yes
        --cluster-config-file nodes.conf
        --cluster-node-timeout 5000
        --appendonly yes
        --bind 0.0.0.0
        --cluster-announce-ip 172.16.7.71
        --cluster-announce-port 7004
        --cluster-announce-bus-port 17004
    ports:
      - "7004:7004"
      - "17004:17004"

  # -------------------------
  # Redis Node 5
  # -------------------------
  redis-node-5:
    image: redis:7.0-alpine
    container_name: redis-node-5
    networks:
      - redis-cluster
    command: >
      redis-server
        --port 7005
        --cluster-enabled yes
        --cluster-config-file nodes.conf
        --cluster-node-timeout 5000
        --appendonly yes
        --bind 0.0.0.0
        --cluster-announce-ip 172.16.7.71
        --cluster-announce-port 7005
        --cluster-announce-bus-port 17005
    ports:
      - "7005:7005"
      - "17005:17005"

  # -------------------------
  # Redis Node 6
  # -------------------------
  redis-node-6:
    image: redis:7.0-alpine
    container_name: redis-node-6
    networks:
      - redis-cluster
    command: >
      redis-server
        --port 7006
        --cluster-enabled yes
        --cluster-config-file nodes.conf
        --cluster-node-timeout 5000
        --appendonly yes
        --bind 0.0.0.0
        --cluster-announce-ip 172.16.7.71
        --cluster-announce-port 7006
        --cluster-announce-bus-port 17006
    ports:
      - "7006:7006"
      - "17006:17006"

  # -------------------------
  # 초기 클러스터 생성용
  # -------------------------
  redis-cluster-init:
    image: redis:7.0-alpine
    container_name: redis-cluster-init
    networks:
      - redis-cluster
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    entrypoint: ["/bin/sh", "-c"]
    command:
      - echo "yes" | redis-cli --cluster create redis-node-1:7001 redis-node-2:7002 redis-node-3:7003 redis-node-4:7004 redis-node-5:7005 redis-node-6:7006 --cluster-replicas 1

networks:
    redis-cluster:
        driver: bridge